name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true
  notification-color:
    description: 'Color of notification header line'
    required: true
  timezone:
    description: 'Timezone (ex. America/Denver)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
